# Generated by Django 4.2.13 on 2024-07-25 12:33

import accounts.constants
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('tier', models.IntegerField(blank=True, choices=[(101, 'FREE'), (102, 'GOLD'), (103, 'DIAMOND')], default=accounts.constants.TierTypes['FREE'], null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
