# Generated by Django 4.2.13 on 2024-07-05 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('caste', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_caste', to='wedlock.caste')),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_range', models.IntegerField(blank=True, choices=[(101, 'Hundred Forty FortyFive'), (102, 'Hundred FortyFive Fifty'), (103, 'Hundred Fifty FiftyFive'), (104, 'Hundred FiftyFive Sixty'), (105, 'Hundred SixtyFive Seventy'), (106, 'Hundred Seventy SeventyFive'), (107, 'Hundred SeventyFive Eighty'), (108, 'Hundred Eighty EightyFive'), (109, 'Hundred EightyFive Ninty')], null=True)),
                ('weight_range', models.IntegerField(blank=True, choices=[(101, 'Forty FortyFive'), (102, 'FortyFive Fifty'), (103, 'Fifty FiftyFive'), (104, 'FiftyFive Sixty'), (105, 'SixtyFive Seventy'), (106, 'Seventy SeventyFive'), (107, 'SeventyFive Eighty'), (108, 'Eighty EightyFive'), (109, 'EightyFive Ninty')], null=True)),
                ('location', models.IntegerField(blank=True, choices=[(101, 'ALAPPUZHA'), (102, 'ERNAKULAM'), (103, 'IDUKKI'), (104, 'KANNUR'), (105, 'KASARAGOD'), (106, 'KoLLAM'), (107, 'KOTTAYAM'), (108, 'KOZHIKODE'), (109, 'MALAPPURAM'), (110, 'PALAKKADd'), (111, 'PATHANAMTHITTA'), (112, 'THIRUVANANTHAPURAM'), (113, 'THRISSUR'), (114, 'WAYANA')], null=True)),
                ('family_type', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('expectations', models.TextField(default='')),
                ('caste', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preference', to='wedlock.caste')),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_type', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('father_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('father_occupation', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('mother_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('mother_occupation', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('no_of_siblings', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('family_values', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=300, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=300, null=True)),
                ('horoscope', models.IntegerField(blank=True, choices=[(101, 'Aries'), (102, 'Taurus'), (103, 'Gemini'), (104, 'Cancer'), (105, 'Leo'), (106, 'Virgo'), (107, 'Libra'), (108, 'Scorpio'), (109, 'Sagittarius'), (110, 'Capricorn'), (111, 'Aquarius'), (112, 'Pisces')], null=True)),
                ('body_type', models.IntegerField(blank=True, choices=[(101, 'SLIM'), (102, 'ATHLETIC'), (103, 'AVERAGE'), (104, 'MUSCULAR'), (105, 'CURVY'), (106, 'PLUS SIZE'), (107, 'PETITE'), (108, 'TALL')], null=True)),
                ('complexion', models.IntegerField(blank=True, choices=[(101, 'FAIR'), (102, 'MEDIUM'), (103, 'BROWN'), (104, 'BLACK')], null=True)),
                ('blood_group', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('dietary', models.IntegerField(blank=True, choices=[(101, 'OMNIVORE'), (102, 'VEGETARIAN'), (103, 'VEGAN'), (104, 'PESCATARIAN'), (105, 'FLEXTARIAN'), (106, 'KETO'), (107, 'GLUTEN FREE'), (108, 'DAIRY FREE')], null=True)),
                ('caste', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='wedlock.caste')),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='caste',
            name='religion',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caste', to='wedlock.religion'),
        ),
    ]
