# Generated by Django 4.2.13 on 2024-07-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedlock', '0002_alter_familyinfo_user_alter_preferences_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='height_range',
            field=models.IntegerField(blank=True, choices=[(101, 'Hundred Forty FortyFive'), (102, 'Hundred FortyFive Fifty'), (103, 'Hundred Fifty FiftyFive'), (104, 'Hundred FiftyFive Sixty'), (105, 'Hundred Sixty SixtyFive'), (106, 'Hundred SixtyFive Seventy'), (107, 'Hundred Seventy SeventyFive'), (108, 'Hundred SeventyFive Eighty'), (109, 'Hundred Eighty EightyFive'), (110, 'Hundred EightyFive Ninty')], null=True),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='weight_range',
            field=models.IntegerField(blank=True, choices=[(101, 'Forty FortyFive'), (102, 'FortyFive Fifty'), (103, 'Fifty FiftyFive'), (104, 'FiftyFive Sixty'), (105, 'Sixty SixtyFive'), (106, 'SixtyFive Seventy'), (107, 'Seventy SeventyFive'), (108, 'SeventyFive Eighty'), (109, 'Eighty EightyFive'), (110, 'EightyFive Ninty')], null=True),
        ),
    ]
