# Generated by Django 4.2.13 on 2024-07-10 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedlock', '0004_userlike_userinterest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinterest',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interested', to='wedlock.client'),
        ),
        migrations.AlterField(
            model_name='userinterest',
            name='receiver',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interest', to='wedlock.client'),
        ),
    ]
