# Generated by Django 4.2.13 on 2024-07-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedlock', '0005_alter_userinterest_owner_alter_userinterest_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlike',
            name='requested',
            field=models.BooleanField(default=True),
        ),
    ]
