# Generated by Django 4.2.13 on 2024-07-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedlock', '0006_userlike_requested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlike',
            name='requested',
        ),
        migrations.AddField(
            model_name='userinterest',
            name='requested',
            field=models.BooleanField(default=True),
        ),
    ]
