# Generated by Django 4.2.13 on 2024-07-13 08:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wedlock', '0007_remove_userlike_requested_userinterest_requested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlike',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='userinterest',
            name='requested_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userlike',
            name='liked_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userinterest',
            name='is_approved',
            field=models.IntegerField(blank=True, choices=[(101, 'REQUESTED'), (102, 'PENDING'), (103, 'APPROVED'), (104, 'REJECTED')], null=True),
        ),
    ]
