# Generated by Django 4.2.13 on 2024-07-13 09:03

from django.db import migrations, models
import django.db.models.deletion
import wedlock.constants


class Migration(migrations.Migration):

    dependencies = [
        ('wedlock', '0008_remove_userlike_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinterest',
            name='is_approved',
            field=models.IntegerField(blank=True, choices=[(101, 'REQUESTED'), (102, 'PENDING'), (103, 'APPROVED'), (104, 'REJECTED')], default=wedlock.constants.RequestStatus['REQUESTED'], null=True),
        ),
        migrations.AlterField(
            model_name='userlike',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked', to='wedlock.client'),
        ),
    ]
