# Generated by Django 4.2.13 on 2024-07-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='projectuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(101, 'Male'), (102, 'Female'), (103, 'Others')], null=True),
        ),
    ]
