# Generated by Django 4.2.13 on 2024-07-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_projectuser_managers_alter_projectuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='is_registered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
