# Generated by Django 4.2.13 on 2024-07-24 07:42

import accounts.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_projectuser_is_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='tier',
            field=models.IntegerField(blank=True, choices=[(101, 'FREE'), (102, 'GOLD'), (103, 'DIAMOND')], default=accounts.constants.TierTypes['FREE'], null=True),
        ),
    ]
