data_dict = [
  {
    "first_name": "John",
    "last_name": "Doe",
    "password": "abcd1234",
    "email": "john.doe@example.com",
    "dob": "1990-01-01",
    "place_of_birth": "CityA",
    "age": 34,
    "gender": 102,
    "languages": "English",
    "user_type": 102,
    "smoking": 101,
    "drinking": 102,
    "hobbies": "Reading",
    "phone": "1234567890",
    "address": "123 Main St, CityA",
    "district": 101,
    "pincode": "123456",
    "is_employ": True,
    "is_short_term": False,
    "preference": {
      "expectations": "Should be kind and supportive",
      "family_type": "Nuclear",
      "height_range": 106,
      "location": 101,
      "weight_range": 104,
      "caste": 5
    },
    "client": {
      "blood_group": "O+ve",
      "body_type": 102,
      "complexion": 101,
      "dietary": 103,
      "height": 175,
      "horoscope": 106,
      "caste": 5,
      "weight": "70.00"
    }
  },
  {
    "first_name": "Jane",
    "last_name": "Smith",
    "password": "efgh5678",
    "email": "jane.smith@example.com",
    "dob": "1988-05-12",
    "place_of_birth": "CityB",
    "age": 36,
    "gender": 101,
    "languages": "Spanish",
    "user_type": 102,
    "smoking": 102,
    "drinking": 103,
    "hobbies": "Traveling",
    "phone": "0987654321",
    "address": "456 Another St, CityB",
    "district": 102,
    "pincode": "654321",
    "is_employ": True,
    "is_short_term": False,
    "preference": {
      "expectations": "Should be honest and loving",
      "family_type": "Joint",
      "height_range": 107,
      "location": 102,
      "weight_range": 105,
      "caste": 6
    },
    "client": {
      "blood_group": "A-ve",
      "body_type": 103,
      "complexion": 102,
      "dietary": 104,
      "height": 160,
      "horoscope": 107,
      "caste": 6,
      "weight": "55.00"
    }
  },
  {
    "first_name": "Michael",
    "last_name": "Johnson",
    "password": "ijkl9012",
    "email": "michael.johnson@example.com",
    "dob": "1995-03-20",
    "place_of_birth": "CityC",
    "age": 29,
    "gender": 102,
    "languages": "French",
    "user_type": 102,
    "smoking": 103,
    "drinking": 101,
    "hobbies": "Gaming",
    "phone": "1122334455",
    "address": "789 New St, CityC",
    "district": 103,
    "pincode": "789123",
    "is_employ": True,
    "is_short_term": False,
    "preference": {
      "expectations": "Should be understanding",
      "family_type": "Nuclear",
      "height_range": 108,
      "location": 103,
      "weight_range": 106,
      "caste": 7
    },
    "client": {
      "blood_group": "B+ve",
      "body_type": 104,
      "complexion": 103,
      "dietary": 105,
      "height": 180,
      "horoscope": 108,
      "caste": 7,
      "weight": "75.00"
    }
  },
  {
    "first_name": "Emily",
    "last_name": "Davis",
    "password": "mnop3456",
    "email": "emily.davis@example.com",
    "dob": "1992-08-14",
    "place_of_birth": "CityD",
    "age": 32,
    "gender": 101,
    "languages": "German",
    "user_type": 102,
    "smoking": 104,
    "drinking": 102,
    "hobbies": "Cooking",
    "phone": "2233445566",
    "address": "101 Old St, CityD",
    "district": 104,
    "pincode": "123789",
    "is_employ": True,
    "is_short_term": False,
    "preference": {
      "expectations": "Should be respectful",
      "family_type": "Joint",
      "height_range": 109,
      "location": 104,
      "weight_range": 107,
      "caste": 8
    },
    "client": {
      "blood_group": "AB-ve",
      "body_type": 105,
      "complexion": 104,
      "dietary": 106,
      "height": 165,
      "horoscope": 109,
      "caste": 8,
      "weight": "60.00"
    }
  },
  {
    "first_name": "David",
    "last_name": "Wilson",
    "password": "qrst7890",
    "email": "david.wilson@example.com",
    "dob": "1998-11-22",
    "place_of_birth": "CityE",
    "age": 26,
    "gender": 102,
    "languages": "Chinese",
    "user_type": 102,
    "smoking": 105,
    "drinking": 103,
    "hobbies": "Hiking",
    "phone": "3344556677",
    "address": "202 High St, CityE",
    "district": 105,
    "pincode": "456123",
    "is_employ": True,
    "is_short_term": False,
    "preference": {
      "expectations": "Should be adventurous",
      "family_type": "Nuclear",
      "height_range": 110,
      "location": 105,
      "weight_range": 108,
      "caste": 9
    },
    "client": {
      "blood_group": "O-ve",
      "body_type": 106,
      "complexion": 101,
      "dietary": 107,
      "height": 170,
      "horoscope": 110,
      "caste": 9,
      "weight": "65.00"
    }
  },
  {
    "first_name": "Sarah",
    "last_name": "Moore",
    "password": "uvwx2345",
    "email": "sarah.moore@example.com",
    "dob": "1985-07-07",
    "place_of_birth": "CityF",
    "age": 39,
    "gender": 101,
    "languages": "Japanese",
    "user_type": 102,
    "smoking": 101,
    "drinking": 104,
    "hobbies": "Yoga",
    "phone": "4455667788",
    "address": "303 Park St, CityF",
    "district": 106,
    "pincode": "789456",
    "is_employ": True,
    "is_short_term": False,
    "preference": {
      "expectations": "Should be patient",
      "family_type": "Joint",
      "height_range": 101,
      "location": 106,
      "weight_range": 101,
      "caste": 10
    },
    "client": {
      "blood_group": "A+ve",
      "body_type": 107,
      "complexion": 102,
      "dietary": 108,
      "height": 155,
      "horoscope": 101,
      "caste": 10,
      "weight": "50.00"
    }
  },
  {
    "first_name": "James",
    "last_name": "Taylor",
    "password": "yzab6789",
    "email": "james.taylor@example.com",
    "dob": "1987-12-30",
    "place_of_birth": "CityG",
    "age": 36,
    "gender": 102,
    "languages": "Russian",
    "user_type": 102,
    "smoking": 102,
    "drinking": 105,
    "hobbies": "Photography",
    "phone": "5566778899",
    "address": "404 River St, CityG",
    "district": 107,
    "pincode": "321654",
    "is_employ": True,
    "is_short_term": False,
    "preference": {
      "expectations": "Should be creative",
      "family_type": "Nuclear",
      "height_range": 102,
      "location": 107,
      "weight_range": 102,
      "caste": 11
    },
    "client": {
      "blood_group": "B-ve",
      "body_type": 103,
      "complexion": 103,
      "dietary": 104,
      "height": 160,
      "horoscope": 102,
      "caste": 11,
      "weight": "55.00"
    }
  },
  {
    "first_name": "Olivia",
    "last_name": "Brown",
    "password": "12345678",
    "email": "olivia.brown@example.com",
    "dob": "1993-04-25",
    "place_of_birth": "CityH",
    "age": 31,
    "gender": 101,
    "languages": "French",
    "user_type": 102,
    "smoking": 103,
    "drinking": 101,
    "hobbies": "Painting",
    "phone": "9876543210",
    "address": "567 Lakeview Dr, CityH",
    "district": 108,
    "pincode": "987654",
    "is_employ": True,
    "is_short_term": False,
    "preference": {
      "expectations": "Should be caring",
      "family_type": "Joint",
      "height_range": 103,
      "location": 108,
      "weight_range": 103,
      "caste": 12
    },
    "client": {
      "blood_group": "AB+ve",
      "body_type": 104,
      "complexion": 104,
      "dietary": 105,
      "height": 168,
      "horoscope": 103,
      "caste": 12,
      "weight": "60.00"
    }
  },
  {
    "first_name": "William",
    "last_name": "Martinez",
    "password": "abcdefgh",
    "email": "william.martinez@example.com",
    "dob": "1986-11-15",
    "place_of_birth": "CityI",
    "age": 38,
    "gender": 102,
    "languages": "Spanish",
    "user_type": 102,
    "smoking": 102,
    "drinking": 104,
    "hobbies": "Playing guitar",
    "phone": "1122334455",
    "address": "789 Oak St, CityI",
    "district": 109,
    "pincode": "112233",
    "is_employ": True,
    "is_short_term": False,
    "preference": {
      "expectations": "Should be understanding",
      "family_type": "Nuclear",
      "height_range": 104,
      "location": 109,
      "weight_range": 104,
      "caste": 13
    },
    "client": {
      "blood_group": "O+ve",
      "body_type": 105,
      "complexion": 101,
      "dietary": 106,
      "height": 172,
      "horoscope": 104,
      "caste": 13,
      "weight": "70.00"
    }
  },
  {
    "first_name": "Sophia",
    "last_name": "Garcia",
    "password": "ijklmnop",
    "email": "sophia.garcia@example.com",
    "dob": "1991-06-10",
    "place_of_birth": "CityJ",
    "age": 33,
    "gender": 101,
    "languages": "Portuguese",
    "user_type": 102,
    "smoking": 101,
    "drinking": 102,
    "hobbies": "Dancing",
    "phone": "3344556677",
    "address": "901 Maple Ave, CityJ",
    "district": 110,
    "pincode": "334455",
    "is_employ": True,
    "is_short_term": False,
    "preference": {
      "expectations": "Should be supportive",
      "family_type": "Joint",
      "height_range": 105,
      "location": 110,
      "weight_range": 105,
      "caste": 14
    },
    "client": {
      "blood_group": "A+ve",
      "body_type": 106,
      "complexion": 102,
      "dietary": 107,
      "height": 165,
      "horoscope": 105,
      "caste": 14,
      "weight": "55.00"
    }
  },
  {
    "first_name": "Benjamin",
    "last_name": "Lopez",
    "password": "qrstuvwx",
    "email": "benjamin.lopez@example.com",
    "dob": "1989-09-05",
    "place_of_birth": "CityK",
    "age": 31,
    "gender": 102,
    "languages": "Chinese",
    "user_type": 102,
    "smoking": 102,
    "drinking": 103,
    "hobbies": "Swimming",
    "phone": "5566778899",
    "address": "345 Elm St, CityK",
    "district": 111,
    "pincode": "556677",
    "is_employ": True,
    "is_short_term": False,
    "preference": {
      "expectations": "Should be adventurous",
      "family_type": "Nuclear",
      "height_range": 106,
      "location": 111,
      "weight_range": 106,
      "caste": 15
    },
    "client": {
      "blood_group": "B-ve",
      "body_type": 103,
      "complexion": 103,
      "dietary": 104,
      "height": 160,
      "horoscope": 106,
      "caste": 15,
      "weight": "60.00"
    }
  },
  {
    "first_name": "Mia",
    "last_name": "Hernandez",
    "password": "yzabcdef",
    "email": "mia.hernandez@example.com",
    "dob": "1994-02-28",
    "place_of_birth": "CityL",
    "age": 30,
    "gender": 101,
    "languages": "Italian",
    "user_type": 102,
    "smoking": 103,
    "drinking": 104,
    "hobbies": "Singing",
    "phone": "1122334455",
    "address": "567 Pine St, CityL",
    "district": 112,
    "pincode": "112233",
    "is_employ": True,
    "is_short_term": False,
    "preference": {
      "expectations": "Should be caring",
      "family_type": "Joint",
      "height_range": 107,
      "location": 112,
      "weight_range": 107,
      "caste": 16
    },
    "client": {
      "blood_group": "O+ve",
      "body_type": 104,
      "complexion": 104,
      "dietary": 105,
      "height": 168,
      "horoscope": 107,
      "caste": 16,
      "weight": "65.00"
    }
  },
  {
    "first_name": "Ethan",
    "last_name": "Gonzalez",
    "password": "ghijklmn",
    "email": "ethan.gonzalez@example.com",
    "dob": "1996-07-15",
    "place_of_birth": "CityM",
    "age": 28,
    "gender": 102,
    "languages": "German",
    "user_type": 102,
    "smoking": 101,
    "drinking": 102,
    "hobbies": "Playing basketball",
    "phone": "3344556677",
    "address": "901 Cedar St, CityM",
    "district": 113,
    "pincode": "334455",
    "is_employ": True,
    "is_short_term": False,
    "preference": {
      "expectations": "Should be supportive",
      "family_type": "Nuclear",
      "height_range": 108,
      "location": 113,
      "weight_range": 108,
      "caste": 17
    },
    "client": {
      "blood_group": "A+ve",
      "body_type": 105,
      "complexion": 102,
      "dietary": 107,
      "height": 165,
      "horoscope": 108,
      "caste": 17,
      "weight": "55.00"
    }
  }
    ]

